"""Tier 1: contract — proposal 0060 Addendum D, D5b (docs-carrier).

Co-vet pins:

  1. **Byte-gate.** ``scripts/mirror_reference_docs.mirror_reference_docs``
     produces a mirror byte-identical to ``docs/reference/`` — every file's
     bytes match, no missing/extra files. Falsify: a mirror that DROPS a file
     (e.g. a future edit that filters ``.ja.md`` files) fails this test —
     verified by mirroring into a filtered copy of the source and asserting
     the completeness check catches it.
  2. **Production-reachability.** ``reyn.builtin.docs.read_builtin_doc``
     reaches a mirrored doc via ``importlib.resources`` (the wheel-install
     path) even when ``resolve_reyn_root()`` — the dev-checkout-only
     mechanism every other ``docs/`` path relies on — is made to raise
     (simulating a wheel install with no repository root). This is the
     reachability fact D5b exists to fix: a pip-installed deploy could not
     previously file-read any reference doc.

No mocks: the mirror function is invoked for real (writing to a temp dir for
the byte-gate, and to the real ``src/reyn/builtin/reference/`` build-hook
location for the reachability test, cleaned up in a fixture). No test asserts
private state; both work through the module's public functions.
"""
from __future__ import annotations

import shutil
from pathlib import Path

import pytest

from scripts.mirror_reference_docs import BUILTIN_MIRROR, DOCS_REFERENCE, mirror_reference_docs


def _all_files(root: Path) -> dict[str, bytes]:
    return {
        str(p.relative_to(root)): p.read_bytes()
        for p in root.rglob("*")
        if p.is_file()
    }


def test_mirror_reproduces_source_content_exactly(tmp_path: Path) -> None:
    """Tier 1: the mirror this function produces matches docs/reference/ byte-for-byte."""
    dst = tmp_path / "mirror"
    mirror_reference_docs(dst=dst, src=DOCS_REFERENCE)

    source_files = _all_files(DOCS_REFERENCE)
    mirrored_files = _all_files(dst)

    assert source_files, "docs/reference/ is unexpectedly empty — nothing to carry"
    assert mirrored_files.keys() == source_files.keys(), (
        "mirror file set diverges from docs/reference/: "
        f"missing={source_files.keys() - mirrored_files.keys()} "
        f"extra={mirrored_files.keys() - source_files.keys()}"
    )
    for rel, content in source_files.items():
        assert mirrored_files[rel] == content, f"{rel}: mirror content diverges from source"


def test_byte_gate_falsifies_on_a_dropped_file(tmp_path: Path) -> None:
    """Tier 1: (falsify) a mirror that drops a source file is caught — the byte-gate is
    not vacuously true regardless of what the mirror actually contains."""
    filtered_src = tmp_path / "filtered_source"
    shutil.copytree(DOCS_REFERENCE, filtered_src)
    dropped = next(p for p in filtered_src.rglob("*") if p.is_file())
    dropped.unlink()

    dst = tmp_path / "mirror_of_filtered"
    mirror_reference_docs(dst=dst, src=filtered_src)

    source_files = _all_files(DOCS_REFERENCE)
    mirrored_files = _all_files(dst)
    assert mirrored_files.keys() != source_files.keys(), (
        "expected the deliberately-dropped file to make the mirror diverge from the "
        "real docs/reference/ source"
    )


@pytest.fixture
def real_builtin_mirror():
    """Generate the mirror at its real build-hook location
    (src/reyn/builtin/reference/), then remove it (git-ignored, regenerated by
    setup.py's build_py hook — never a committed artifact)."""
    mirror_reference_docs(dst=BUILTIN_MIRROR, src=DOCS_REFERENCE)
    try:
        yield BUILTIN_MIRROR
    finally:
        if BUILTIN_MIRROR.exists():
            shutil.rmtree(BUILTIN_MIRROR)


def test_production_reachability_survives_no_repo_root(real_builtin_mirror, monkeypatch) -> None:
    """Tier 1: (falsify) simulating a wheel install (resolve_reyn_root raises — no
    co-located pyproject.toml, the hard production fact D5b exists to fix), the
    reference doc is still reachable via the builtin tier's importlib.resources path."""
    from reyn.builtin import docs as builtin_docs

    def _raise(*args, **kwargs):
        raise RuntimeError("simulated wheel install: no reyn repository root found")

    monkeypatch.setattr("reyn.runtime.reyn_src.resolve_reyn_root", _raise)

    rel_path = "runtime/pipeline-dsl.md"
    assert (DOCS_REFERENCE / rel_path).is_file(), "fixture doc path must exist in the real tree"

    content = builtin_docs.read_builtin_doc(rel_path)
    # Behavioral assertion (not a golden-file pin): the reader must have reached
    # THIS specific doc's real content, not an empty/placeholder/wrong file —
    # checked via a distinctive marker line from the doc's own front-matter
    # (search_hints), never the doc's exact byte length or formatting.
    assert "pipeline DSL" in content
    assert "search_hints" in content


def test_reachability_without_the_mirror_raises_doc_not_found(monkeypatch, tmp_path) -> None:
    """Tier 1: (falsify) with NEITHER the builtin mirror NOR a resolvable repo root, the
    reader raises a loud DocNotFoundError instead of silently returning nothing —
    proving the production-reachability test above is exercising a real fallback
    chain, not a path that always "works" some other way."""
    from reyn.builtin import docs as builtin_docs

    assert not BUILTIN_MIRROR.exists(), (
        "this test requires the mirror to be absent; a prior test left it behind"
    )

    def _raise(*args, **kwargs):
        raise RuntimeError("simulated wheel install: no reyn repository root found")

    monkeypatch.setattr("reyn.runtime.reyn_src.resolve_reyn_root", _raise)

    with pytest.raises(builtin_docs.DocNotFoundError):
        builtin_docs.read_builtin_doc("runtime/pipeline-dsl.md")
