"""Compaction engine — multi-axis OS-internal compaction (chat / planner step / phase)."""
from reyn.services.compaction.engine import (
    ChatSummary,
    ChatSummaryRaw,
    CompactionEngine,
    CompactionOverflowError,
    ComputedBudgets,
    ContextOverflowError,
    ForceCompactRaceUnrecoveredError,
    HistoryChunkToCompact,
    NewMsgExceedsBudgetError,
    UnrecoveredError,
    assert_static_bounds,
    compact_control_ir_results,
    compute_budgets,
    compute_covers_through_seq,
    estimate_tokens,
    estimate_tokens_for_turn,
    hard_truncate_summary,
    retry_loop,
    trim_head,
    trim_tail,
)

__all__ = [
    "CompactionEngine",
    "ChatSummary",
    "ChatSummaryRaw",
    "ComputedBudgets",
    "CompactionOverflowError",
    "ContextOverflowError",
    "HistoryChunkToCompact",
    "ForceCompactRaceUnrecoveredError",
    "NewMsgExceedsBudgetError",
    "UnrecoveredError",
    "assert_static_bounds",
    "compact_control_ir_results",
    "compute_budgets",
    "compute_covers_through_seq",
    "estimate_tokens",
    "estimate_tokens_for_turn",
    "hard_truncate_summary",
    "retry_loop",
    "trim_head",
    "trim_tail",
]
