"""Build-time hook: mirror ``docs/reference/`` into the builtin tier.

Proposal 0060 Addendum D, D5b. ``resolve_reyn_root()``
(``src/reyn/runtime/reyn_src.py``) walks up from ``reyn.__file__`` looking for
a co-located ``pyproject.toml`` — that file (and ``docs/``) is never shipped in
a wheel, so in a production (pip) install every ``docs/`` path is unreachable.
The builtin tier (``src/reyn/builtin/``, F3a proposal 0060 Phase 1, PR #2907)
IS packaged (``[tool.setuptools.package-data] "reyn" = [..., "builtin/**/*"]``
in ``pyproject.toml``) and is resolvable via ``importlib.resources`` in a wheel
install with no repo root. This module copies ``docs/reference/`` into
``src/reyn/builtin/reference/`` so the existing packaging glob ships it.

**No committed duplicate** (owner's clean-end-state preference): the
destination directory is regenerated by this function before every
sdist/wheel build (wired into ``setup.py``'s custom ``build_py`` command) and
is git-ignored — ``docs/reference/`` stays the single committed source of
truth. A dev/editable install that never ran the build hook (the mirror
directory absent) falls back to reading ``docs/reference/`` directly via
``resolve_reyn_root()`` (see ``reyn.builtin.docs.read_builtin_doc``).

The byte-gate CI test (``tests/test_0060_d5b_docs_mirror.py``) asserts the
mirror this function produces is byte-identical to ``docs/reference/`` —
drift between the two is impossible by construction (this function is a
straight ``shutil.copytree``, not a distillation), but the test exists so a
FUTURE edit that turns this into something lossy (e.g. filtering files) fails
loudly instead of silently shipping a stale/partial mirror.
"""
from __future__ import annotations

import shutil
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS_REFERENCE = REPO_ROOT / "docs" / "reference"
BUILTIN_MIRROR = REPO_ROOT / "src" / "reyn" / "builtin" / "reference"


def mirror_reference_docs(
    dst: Path = BUILTIN_MIRROR, src: Path = DOCS_REFERENCE,
) -> Path:
    """Copy ``src`` (``docs/reference/``) to ``dst``, byte-identical, idempotent.

    Removes any stale ``dst`` first so a rename/delete upstream in ``docs/`` is
    reflected (never a union of old+new files).
    """
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst)
    return dst


if __name__ == "__main__":
    mirror_reference_docs()
