"""website/build.py — substitute {{TOKEN}} placeholders into index.html.

Reads ``website/copy.yaml`` (the single source of truth for body copy) and
``website/index.html`` (the Claude-Design-generated structural template),
then writes ``website/dist/index.html`` ready for deployment.

Usage::

    python website/build.py

Behavior:

* Every ``{{TOKEN}}`` in ``index.html`` is replaced by ``copy[TOKEN]``.
* Values are inserted as raw HTML — wrap accent words in ``<em>...</em>``
  for the brand clay colour rendering.
* Tokens missing from ``copy.yaml`` are left in place and printed to
  stderr; the script exits with code 2 in that case.
* Keys in ``copy.yaml`` that no template token references are warned
  about (they don't fail the build).

Why this script exists
----------------------
``index.html`` is regenerated by Claude Design from time to time. We don't
want to re-edit body copy after every regeneration. Keeping placeholders
in the template and the real copy in YAML lets the two sources evolve
independently — see the comment block at the top of ``copy.yaml`` and the
note in ``website/_design/claude_design_prompt.md``.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).parent
COPY_FILE = ROOT / "copy.yaml"
TEMPLATE = ROOT / "index.html"
OUT_DIR = ROOT / "dist"
OUT_FILE = OUT_DIR / "index.html"

_TOKEN_RE = re.compile(r"\{\{(\w+)\}\}")


def main() -> int:
    if not COPY_FILE.exists():
        print(f"error: {COPY_FILE} not found", file=sys.stderr)
        return 1
    if not TEMPLATE.exists():
        print(f"error: {TEMPLATE} not found", file=sys.stderr)
        return 1

    raw = COPY_FILE.read_text(encoding="utf-8")
    copy = yaml.safe_load(raw)
    if not isinstance(copy, dict):
        print(f"error: {COPY_FILE} must be a flat YAML mapping", file=sys.stderr)
        return 1

    html = TEMPLATE.read_text(encoding="utf-8")

    used: set[str] = set()
    missing: list[str] = []

    def repl(m: "re.Match[str]") -> str:
        key = m.group(1)
        if key in copy:
            used.add(key)
            value = copy[key]
            if value is None:
                value = ""
            # Strip exactly one trailing newline so YAML's `>-` folded
            # scalars don't introduce a stray newline before the closing
            # tag in the substituted spot.
            return str(value).rstrip("\n")
        missing.append(key)
        return m.group(0)

    out_html = _TOKEN_RE.sub(repl, html)

    unused = sorted(set(copy.keys()) - used)
    if unused:
        print(
            "warning: keys in copy.yaml not referenced by template: "
            + ", ".join(unused),
            file=sys.stderr,
        )

    if missing:
        unique_missing = sorted(set(missing))
        print(
            "error: tokens used in template but missing from copy.yaml: "
            + ", ".join(unique_missing),
            file=sys.stderr,
        )

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(out_html, encoding="utf-8")

    print(
        f"wrote {OUT_FILE.relative_to(ROOT.parent)} "
        f"({len(out_html):,} bytes; {len(used)} tokens substituted)"
    )

    return 2 if missing else 0


if __name__ == "__main__":
    sys.exit(main())
