"""website/build.py — substitute {{TOKEN}} placeholders into HTML pages.

Reads ``website/copy.yaml`` (the single source of truth for body copy) and
the Claude-Design-generated structural templates listed in ``TEMPLATES``,
then writes substituted output under ``website/dist/`` ready for deploy.

Usage::

    python website/build.py

Behavior:

* Every ``{{TOKEN}}`` in each template is replaced by ``copy[TOKEN]``.
* Values are inserted as raw HTML — wrap accent words in ``<em>...</em>``
  for the brand clay colour rendering.
* Tokens missing from ``copy.yaml`` are left in place and printed to
  stderr; the script exits with code 2 in that case.
* Keys in ``copy.yaml`` that no template references (across ALL templates)
  are warned about (they don't fail the build).

Why this script exists
----------------------
The HTML templates are regenerated by Claude Design from time to time.
We don't want to re-edit body copy after every regeneration. Keeping
placeholders in templates and the real copy in YAML lets the two sources
evolve independently — see the comment block at the top of ``copy.yaml``
and the note in ``website/_design/claude_design_prompt.md``.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).parent
COPY_FILE = ROOT / "copy.yaml"
OUT_DIR = ROOT / "dist"

# Each template is a source HTML file; output lands at the same name under dist/.
TEMPLATES: list[str] = ["index.html", "architecture.html"]

_TOKEN_RE = re.compile(r"\{\{(\w+)\}\}")


def _substitute(html: str, copy: dict, used: set[str], missing: list[str]) -> str:
    def repl(m: "re.Match[str]") -> str:
        key = m.group(1)
        if key in copy:
            used.add(key)
            value = copy[key]
            if value is None:
                value = ""
            # Strip exactly one trailing newline so YAML's `>-` folded
            # scalars don't introduce a stray newline before the closing
            # tag in the substituted spot.
            return str(value).rstrip("\n")
        missing.append(key)
        return m.group(0)

    return _TOKEN_RE.sub(repl, html)


def main() -> int:
    if not COPY_FILE.exists():
        print(f"error: {COPY_FILE} not found", file=sys.stderr)
        return 1

    raw = COPY_FILE.read_text(encoding="utf-8")
    copy = yaml.safe_load(raw)
    if not isinstance(copy, dict):
        print(f"error: {COPY_FILE} must be a flat YAML mapping", file=sys.stderr)
        return 1

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    used: set[str] = set()
    missing: list[str] = []
    wrote: list[tuple[Path, int, int]] = []  # (path, bytes, tokens_in_file)

    for name in TEMPLATES:
        template = ROOT / name
        if not template.exists():
            print(f"error: {template} not found", file=sys.stderr)
            return 1

        html = template.read_text(encoding="utf-8")
        before = len(used)
        out_html = _substitute(html, copy, used, missing)
        out_file = OUT_DIR / name
        out_file.write_text(out_html, encoding="utf-8")
        wrote.append((out_file, len(out_html), len(used) - before))

    unused = sorted(set(copy.keys()) - used)
    if unused:
        print(
            "warning: keys in copy.yaml not referenced by any template: "
            + ", ".join(unused),
            file=sys.stderr,
        )

    if missing:
        unique_missing = sorted(set(missing))
        print(
            "error: tokens used in templates but missing from copy.yaml: "
            + ", ".join(unique_missing),
            file=sys.stderr,
        )

    for out_file, size, n_tokens in wrote:
        print(
            f"wrote {out_file.relative_to(ROOT.parent)} "
            f"({size:,} bytes; {n_tokens} new tokens substituted)"
        )

    return 2 if missing else 0


if __name__ == "__main__":
    sys.exit(main())
