"""Git worktree + web-server lifecycle helpers."""
from __future__ import annotations

import os
import subprocess
import time
from pathlib import Path

from spike_lib.http import get_url


def worktree_path(branch: str) -> Path:
    """Return the /tmp worktree path for a given branch name."""
    safe = branch.replace("/", "-").replace(".", "-")
    return Path(f"/tmp/reyn-spike-{safe}")


def ensure_worktree(project_root: Path, branch: str, worktree: Path) -> None:
    """Create git worktree if it doesn't exist; reuse if it does."""
    if worktree.exists():
        return
    print(f"[worktree] creating {worktree} for branch {branch!r}", flush=True)
    result = subprocess.run(
        ["git", "worktree", "add", str(worktree), branch],
        cwd=str(project_root),
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"git worktree add failed for branch {branch!r}:\n"
            f"  stdout: {result.stdout.strip()}\n"
            f"  stderr: {result.stderr.strip()}"
        )
    print(f"[worktree] created {worktree}", flush=True)


def write_model_override(worktree: Path, model_class: str, strong_model: str) -> None:
    """Inject reyn.local.yaml to override the model mapping."""
    local_yaml = worktree / "reyn.local.yaml"
    content = (
        f"# Auto-generated by dogfood_g4_spike.py — do not edit by hand.\n"
        f"model: {model_class}\n"
        f"models:\n"
        f"  strong: {strong_model}\n"
    )
    local_yaml.write_text(content, encoding="utf-8")


def remove_model_override(worktree: Path) -> None:
    """Remove the injected reyn.local.yaml if present."""
    local_yaml = worktree / "reyn.local.yaml"
    if local_yaml.exists():
        local_yaml.unlink()


def start_web_server(
    worktree: Path, port: int, env_extras: dict[str, str]
) -> subprocess.Popen:  # type: ignore[type-arg]
    env = {**os.environ, **env_extras}
    return subprocess.Popen(
        ["reyn", "web", "--port", str(port)],
        cwd=str(worktree),
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )


def wait_for_server(port: int, timeout_s: float = 30.0) -> bool:
    url = f"http://localhost:{port}/healthz"
    deadline = time.monotonic() + timeout_s
    while time.monotonic() < deadline:
        if get_url(url, timeout=2.0):
            return True
        time.sleep(1.0)
    return False


def stop_web_server(proc: subprocess.Popen) -> None:  # type: ignore[type-arg]
    if proc.poll() is None:
        proc.terminate()
        try:
            proc.wait(timeout=10)
        except subprocess.TimeoutExpired:
            proc.kill()
            proc.wait()
